feedback/urls.py
from django.conf.urls import url

from . import views

app_name='feedback'

urlpatterns = [
    url(r"^$", views.FeedbackList.as_view(), name="all"),
    url(r"new/$", views.CreateFeedback.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserFeedback.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.FeedbackDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteFeedback.as_view(),name="delete"),
]

projects/urls.py
from django.conf.urls import url

from . import views

app_name = 'projects'

urlpatterns = [
    url(r"^$", views.ListProjects.as_view(), name="all"),
    url(r"^new/$", views.CreateProject.as_view(), name="create"),
    url(r"^feedback/in/(?P<slug>[-\w]+)/$",views.SingleProject.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinProject.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveProject.as_view(),name="leave"),
]

xbrief/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r"^feedback/", include("feedback.urls", namespace="feedback")),
    url(r"^projects/",include("projects.urls", namespace="projects")),

]

projects/models.py
from django.db import models
from django.utils.text import slugify #This will lowercase and add dashes to ulr slug
from django.core.urlresolvers import reverse
# Create your models here.

import misaka

from django.contrib.auth import get_user_model

User = get_user_model()

from django import template
register = template.Library() # This is how we can use custom template tags in the futre

class Project(models.Model): # I have replaced Group with Project
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="ProjectMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self): #have replaced groups with projects below
        return reverse("projects:single", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["name"]

class ProjectMember(models.Model):
    project = models.ForeignKey(Project, related_name='memberships')
    user = models.ForeignKey(User, related_name='user_projects')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('project', 'user')

projects/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from projects.models import Project,ProjectMember
from . import models

class CreateProject(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description") #These are the fields a user is able to edit
    model = Project

class SingleProject(generic.DetailView):
    model = Project

class ListProjects(generic.ListView):
    model = Project


class JoinProject(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("projects:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project,slug=self.kwargs.get("slug"))

        try:
            ProjectMember.objects.create(user=self.request.user,project=project)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(project.name)))

        else:
            messages.success(self.request,"You are now a member of the {} project.".format(project.name))

        return super().get(request, *args, **kwargs)


class LeaveProject(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("projects:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.ProjectMember.objects.filter(
                user=self.request.user,
                project__slug=self.kwargs.get("slug")
            ).get()

        except models.ProjectMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this project because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this project."
            )
        return super().get(request, *args, **kwargs)

projects/templates/projects/project_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block preproject %}{% endblock %}
    {% block project_content %}{% endblock %}
    {% block postproject %}{% endblock %}
  </div>
</div>

{% endblock %}

projects/templates/projects/project_detail.html
{% extends "projects/project_base.html" %}

{% block preproject %}


<h1>{{project.name}}</h1>
<h2> Member Count: {{project.members.count}}</h2>

  <div class="content">


				{% if user in project.members.all %}
					<a href="{% url 'projects:leave' slug=project.slug %}" class="btn btn-lg btn-fill btn-warning"><i class="material-icons">exposure_neg_1</i> Leave</a>
				{% else %}
					<a href="{% url 'projects:join' slug=project.slug %}" class="btn btn-lg btn-fill btn-warning"><i class="material-icons">person_add</i> Join</a>
				{% endif %}



</div>

{% endblock %}


{% block project_content %}

<div class="col-md-8">
	{% if project.feedback.count == 0 %}
	<h2>No feedback in this project yet!</h2>

	{% else %}

		{% for feedback in project.feedback.all %}
			{% include "feedback/_feedback.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}

projects/templates/projects/project_form.html
{% extends "projects/project_base.html" %}
{% load bootstrap3 %}

{% block project_content %}
<h4>Create a new project</h4>
  <form method="POST" action="{% url 'projects:create' %}" id="projectForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

projects/templates/projects/project_list.html
{% extends "projects/project_base.html" %}

{% block preproject %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back to xbrief
			<a href="{% url 'feedback:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Projects</h2>

			<p>Welcome to the projects page! Please select the project you would like to give feedback for</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'projects:create' %}" class="btn btn-md btn-fill btn-warning"><i class="material-icons">library_books</i> Create New Project!</a>
	{% endif %}
</div>
{% endblock %}

{% block project_content %}
<div class="col-md-8">
	<div class="list-project">
		{% for project in object_list %}
		  <a class="list-project-item" href="{% url 'projects:single' slug=project.slug %}">
			     <h3 class="title list-project-item-heading">{{ project.name }}</h3>
			<div class="list-project-item-text container-fluid">
				{{ project.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ project.members.count }} </span> member
						<!-- {{ project.members.count }} -->
					</div>
					<div class="col-md-4">
						<span class="badge">{{ project.feedback.count }} </span> feedback
						<!-- {{ project.feedback.count }} -->
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}