accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'login/$',
    auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    url(r'logout/$',
    auth_views.LogoutView.as_view(),
    name='logout'),
    url(r'signup/$',views.SignUp.as_view(),name='signup'),

]

feedback/urls.py
from django.conf.urls import url

from . import views

app_name='feedback'

urlpatterns = [
    url(r"^$", views.FeedbackList.as_view(), name="all"),
    url(r"new/$", views.CreateFeedback.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserFeedback.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.FeedbackDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteFeedback.as_view(),name="delete"),
]

xbrief/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r"^feedback/", include("feedback.urls", namespace="feedback")),
    url(r"^projects/",include("projects.urls", namespace="projects")),

]

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'xbrief/img/apple-icon.png'%}" />
    <link rel="icon" type="image/png" href="{% static 'xbrief/img/logo.png'%}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>xBrief</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'xbrief/css/bootstrap.min.css'%}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'xbrief/css/material-dashboard.css'%}" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>

    <!-- Static here means "go look in the static directory we created in the settings.py file " -->

  <link rel="stylesheet" href="{% static 'xbrief/css/master.css'%}">

  </head>
  <body>
    <div class="wrapper">

        <div class="sidebar" data-color="purple" data-image="{% static 'xbrief/img/sidebar-1.jpg'%}">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="logo">
                <a href="http://127.0.0.1:8000" class="simple-text">
                    XBRIEF
                </a>
            </div>
            <div class="sidebar-wrapper">

                            {% if user.is_authenticated %}
                                <ul class="nav">
                                  <li>
                                      <a href="{% url 'feedback:create' %}">
                                          <i class="material-icons text-gray">question_answer</i>
                                          <p>Feedback</p>
                                      </a>
                                  </li>

                                  <li>
                                      <a href="{% url 'projects:all' %}">
                                          <i class="material-icons">content_paste</i>
                                          <p>Projects</p>
                                      </a>
                                  </li>

                                  <li>
                                      <a href="{% url 'projects:create' %}">
                                          <i class="material-icons">library_books</i>
                                          <p>Create Project</p>
                                      </a>
                                  </li>

                                  <li>
                                      <a href="{% url 'accounts:logout' %}">
                                          <i class="material-icons">person</i>
                                          <p>Log out</p>
                                      </a>
                                  </li>



                                </ul>
                            {% else %}
                            <ul class="nav">
                            <li>
                                <a href="{% url 'accounts:login' %}">
                                    <i class="material-icons">lock</i>
                                    <p>Log in</p>
                                </a>
                            </li>

                            <li>
                                <a href="{% url 'accounts:signup' %}">
                                    <i class="material-icons">person</i>
                                    <p>Sign up</p>
                                </a>
                            </li>

                          </ul>
                            {% endif %}

            </div>
        <div class="sidebar-background" style="background-image: url({% static 'xbrief/img/sidebar-1.jpg) '%}"></div></div>


        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>
                    <div class="collapse navbar-collapse">

                        <form class="navbar-form navbar-right" role="search">
                            <div class="form-group is-empty">
                                <input type="text" class="form-control" placeholder="Search">
                                <span class="material-input"></span>
                            <span class="material-input"></span></div>
                            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                <i class="material-icons">search</i>
                                <div class="ripple-container"></div>
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">xBrief</h4>
                                    <p class="category">We make emails happen.</p>
                                </div>
                                <div class="card-content">
                                  <div class="container mycontent">
                                    {% block content %}



                                    {% endblock %}
                                  </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="#">
                                    Book a Meeting
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Intranet
                                </a>
                            </li>
                            
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        <a href="http://www.xdode.co.za">XDODE</a>, made with love for a better web
                    </p>
                </div>
            </footer>

        </div>



    </div>
  </body>

  <script src="{% static 'xbrief/js/jquery-3.2.1.min.js'%}" type="text/javascript"></script>
  <script src="{% static 'xbrief/js/bootstrap.min.js'%}" type="text/javascript"></script>
  <script src="{% static 'xbrief/js/material.min.js'%}" type="text/javascript"></script>
  <!--  Charts Plugin -->
  <!-- <script src="{% static 'xbrief/js/chartist.min.js'%}"></script> -->
  <!--  Dynamic Elements plugin -->
  <script src="{% static 'xbrief/js/arrive.min.js'%}"></script>
  <!--  PerfectScrollbar Library -->
  <script src="{% static 'xbrief/js/perfect-scrollbar.jquery.min.js'%}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'xbrief/js/bootstrap-notify.js'%}"></script>
  <!--  Google Maps Plugin    -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Material Dashboard javascript methods -->
  <script src="{% static 'xbrief/js/material-dashboard.js'%}"></script>

  <script type="text/javascript" src="{% static 'xbrief/js/master.js' %}">

  </script>
</html>

templates/index.html
{% extends "base.html" %}


    {% block content %}

    <h1>Welcome to xBrief</h1>

    {% endblock %}

templates/test.html
{% extends "base.html" %}

{% block content %}

  <h1>You are now logged in </h1>

{% endblock%}

templates/thanks.html
{% extends "base.html" %}

{% block content %}

  <h1>Thank you for using xbrief. Come back soon.</h1>

{% endblock%}