feedback/urls.py
from django.conf.urls import url

from . import views

app_name='feedback'

urlpatterns = [
    url(r"^$", views.FeedbackList.as_view(), name="all"),
    url(r"new/$", views.CreateFeedback.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserFeedback.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.FeedbackDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeleteFeedback.as_view(),name="delete"),
]

xbrief/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r"^feedback/", include("feedback.urls", namespace="feedback")),
    url(r"^projects/",include("projects.urls", namespace="projects")),

]

feedback/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

import misaka

from projects.models import Project

from django.contrib.auth import get_user_model
User = get_user_model()


class Feedback(models.Model):
    user = models.ForeignKey(User, related_name="feedback")
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    project = models.ForeignKey(Project, related_name="feedback",null=True, blank=True) #Every feedback belongs to a group there ForeignKey

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs) #TODO Need to research what this function does

    def get_absolute_url(self):
        return reverse(
            "feedback:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

feedback/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class FeedbackList(SelectRelatedMixin, generic.ListView):
    model = models.Feedback
    select_related = ("user", "project")


class UserFeedback(generic.ListView):
    model = models.Feedback
    template_name = "feedback/user_feedback_list.html"

    def get_queryset(self):
        try:
            self.feedback_user = User.objects.prefetch_related("feedback").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.feedback_user.feedback.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["feedback_user"] = self.feedback_user
        return context


class FeedbackDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Feedback
    select_related = ("user", "project")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreateFeedback(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','project') #the fields we want people to be able to edit
    model = models.Feedback

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form): #This connects the post to the user
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeleteFeedback(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Feedback
    select_related = ("user", "project")
    success_url = reverse_lazy("feedback:all")#once you have deleted a post it will show you all remaining feedback

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Feedback Deleted")
        return super().delete(*args, **kwargs)

feedback/templates/feedback/_feedback.html
<div class="feedback media">
	<h3>{{ feedback.message_html|safe }}</h3>
	<div class="media-body">
		<strong>{{ feedback.user.username }}</strong>
		<h5 class="media-heading">
			<span class="username"><a href="{% url 'feedback:for_user' username=feedback.user.username %}">@{{ feedback.user.username }}</a></span>
			<time class="time"><a href="{% url 'feedback:single' username=feedback.user.username pk=feedback.pk %}">{{ feedback.created_at }}</a></time>
			{% if feedback.project %}
			<span class="project-name">in <a href="#">{{ feedback.project.name }}</a></span>
			{% endif %}
		</h5>

		<div class="media-footer">
			{% if user.is_authenticated and feedback.user == user and not hide_delete %}
				<a href="{% url 'feedback:delete' pk=feedback.pk %}" title="delete" class="btn btn-simple">
					<span class="btn btn-danger btn-large"><i class="material-icons">warning</i>  Delete</span>





				</a>
			{% endif %}
		</div>
	</div>
</div>

feedback/templates/feedback/feedback_base.html
{% extends "base.html" %}

{% block content %}

<!-- Feedback-page css has nto been configured yet  -->
<div class="feedback-page">
 <div class="container">
   <div class="row">
     {% block pre_feedback %}{% endblock %}
     {% block feedback_content %}{% endblock %}
    {% block feedback_post %}{% endblock %}
   </div>
 </div>
</div>
{% endblock %}

feedback/templates/feedback/feedback_confirm_delete.html
{% extends "feedback/feedback_base.html" %}


{% block feedback_content %}
<h3>Are you sure you want to delete this feedback?</h3>

<div class="feedback">
	{% include "feedback/_feedback.html" with feedback=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'feedback:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

feedback/templates/feedback/feedback_detail.html
{% extends "feedback/feedback_base.html" %}

{% block feedback_content %}
<div class="col-md-8">
    {% include "feedback/_feedback.html" %}
</div>
{% endblock %}

feedback/templates/feedback/feedback_form.html
{% extends "feedback/feedback_base.html" %}

{% load bootstrap3 %}

{% block feedback_content %}
<h4>Create New Feedback</h4>
<form method="POST" action="{% url 'feedback:create' %}" id="feedbackForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>
{% endblock %}

feedback/templates/feedback/feedback_list.html
{% extends "feedback/feedback_base.html" %}
{% load humanize %}

{% block pre_feedback_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_projects as user_projects %}#}
				{% for member_project in get_user_projects %}
				<li class="project li-with-bullet">
					<a href="{% url 'projects:single' slug=member_project.project.slug %}">{{ member_project.project.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All Projects</h5>
			<ul class="list-unstyled">
				{# {% get_other_projects as other_projects %}#}
				{% for other_project in get_other_projects %}
					<li class="project li-with-bullet"><a href="{% url 'projects:single' slug=other_project.slug %}">{{ other_project.name }}</a></li>
				{% endfor %}
			</ul>




		</div>
	</div>
</div>
{% endblock %}

{% block feedback_content %}
<div class="col-md-8">
	{% for feedback in feedback_list %}
  {% include "feedback/_feedback.html" %}
	{% endfor %}
</div>
{% endblock %}

feedback/templates/feedback/user_feedback_list.html
{% extends "feedback/feedback_base.html" %}

{% block prefeedback %}
<div class="col-md-4">
	<h1>@{{ feedback_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block feedback_content %}
<div class="col-md-8">
	{% for feedback in feedback_list %}
		{% include "feedback/_feedback.html" %}
	{% endfor %}
</div>
{% endblock %}